Add ability to use external fidir file

diff --git a/ofx2 b/ofx2
--- a/ofx2
+++ b/ofx2
@@ -17,13 +17,18 @@ set -Eeu #o pipefail
 requirements=( ofx2xml jq xq )
 hashing_requirement=mlr # required for using the -h hash option
 
+
 usage(){ echo '
-Usage: ofx2 [-h|--help|-H] <command> [OPTIONS] <ofx_file> [<ofx_file2> ...]
+Usage: ofx2 [OPTIONS] <subcommand> [OPTIONS] <ofx-file> [<ofx-file2> ...]
 
-The -h and --help options will print this message and quit.
-The -H option will print a list of properties available to formatting options.
+Pre-subcommand options:
+   -h, --help    Print this message and quit.
+   -H            Print a list of properties available to formatting options
+                 and quit.
+   -D  <fidir>   Specify the path to a directory of financial institutions.
+                 (See below for details.)
 
-Otherwise, <command> must be one of the following:
+Unless the first option quits, <sub-command> must be one of the following:
 
    csv    Print transactions as comma-separated values (see below for options)
    tsv    Print transactions as tab-separated values (see below for options)
@@ -62,7 +67,7 @@ Option arguments
 
       <array>   jq-parsed array like `[.ACCTID, .DTPOSTED, "$"+.TRNAMT]`
                 note that square brackets are mandatory.
-      <format>  jq-parsed value like `.INTBUD+"-"+.ACCTID` or `"foo"`.
+      <format>  jq-parsed value like `.FIFID+"-"+.ACCTID` or `"foo"`.
                 note that literal strings must be quoted.
       <mlrexp>  passed to miller to generate the value of hash to be
                 added as an additional field in each transaction.
@@ -83,9 +88,8 @@ options, use `ofx2 -V`.
 declare -A PRESET_DESCRIPTIONS PRESET_FORMATS
 define_preset(){ PRESET_DESCRIPTIONS[$1]="$2"; PRESET_FORMATS[$1]="$3"; }
 define_preset range 'date range of transactions' '.DSTART + " to " + .DEND'
-define_preset bank 'name of financial institution' '.BNM'
-define_preset bnk 'abbreivated name of financial institution' '.BNS'
-define_preset baank 'full name of financial institution' '.BNL'
+define_preset bank 'name of financial institution' '.FIORG'
+define_preset fid 'id of financial institution' '.FIFID'
 define_preset account 'account number, as it appears in OFX file' '.ACCTID'
 
 
@@ -93,19 +97,34 @@ define_preset account 'account number, as it appears in OFX file' '.ACCTID'
 # They are indexed by their INTU.BID value.
 # INTU.BID is a Inutuit Bank ID; the values for North-American institutions can be found here:
 # https://ofx-prod-filist.intuit.com/qm2400/data/fidir.txt
-jq_fidir='
-{
-  "00002": {"short": "TD",   "medium": "TD Canada Trust", "long": "Toronto Dominion Canada Trust" },
-  "00004": {"short": "FK",   "medium": "FK Canada Fake",  "long": "Fakey Fake Financial Canada" },
-  "00005": {"short": "CIBC", "medium": "CIBC",            "long": "Canadian Imperial Bank of Commerce" },
-  "00015": {"short": "RBC",  "medium": "RBC RoyalBank",   "long": "Royal Bank of Canada" },
-  "00024": {"short": "PC",   "medium": "PC Financial",    "long": "President'"'"'s Choice Financial" }
-}
-'
+#
+# this file is not utf-8, my guess is that it is Windows-1252
+# (and not iso-8859-1 becuase it contains some N-dashes.)
+# ot also has a two-line header that must be deleted.
+# Convert it with the command:
+# iconv -f WINDOWS-1252 -t UTF-8 fidir.txt | tr -d '\r' | tail -n +3 | sort > fidir-headless-sorted-utf8.tsv
+#
+# FIDIR_FILE="$HOME/.local/share/ofx2/fidir-headless-sorted-utf8.tsv"
+# provide a regex that will be deleted from .FIORG values
+# that are found by looking them up in the FIDIR_FILE
+FIORG_REGEX_DELETE=' - (English|français)$'
 
+# Include here financial institutions that are frequently used,
+# and ones where you want to use a custom name for.
+# Notes these are only used if there is not <FI><ORG> tag
+# in the original OXF file. Those will always be used.
+fidir_json(){ cat <<EOF
+{
+"00004": "Fakebank",
+"00024": "PC Financial"
+}
+EOF
+}
+
+# This joins NAME and MEMO tags to make a .DESC property.
 jq_description_delimiter='; '
 
-# Noe on the NAMING CONVENTION for variables:
+# Note on the NAMING CONVENTION for variables:
 #   a leading jq_ indicates the string is a fragment of jq code.
 #   a leading mlr_ indicates a fragment of mlr code.
 
@@ -125,23 +144,21 @@ These three properties are always available:
 The following properties are usually available from an OFX file,
 they have the same name as the tags in the OFX file:
 
-   .INTBID     Intuit's Bank ID, stored in the <INTU.BID> tag.
-               This will be read from a <FID><ID> tag if there
-	       is no <INTU.BID> tag present.
+   .FIFID      This will be read from a <FI><FID> tag.
+               (The oxf2xml populates this with <INTU.BID>)
+   .FIORG      This will be read from a <FI><ORG> tag, which
+               may be empty, in which case there will be an attempt
+               to use .FIFID to look up its value, failing that,
+               .FIFID will be used.
    .BANKID     A nine-digit number. According to the OFX spec, this
                should be a routing number, but don't count on that.
+               (It might just be weird for Canadian institutions.)
    .ACCTID     Account number. This may contain spaces and hyphens.
    .ACCTTYPE   Type of account; one of: Bank, Credit.
                (Other types will probably cause this script to fail.)
    .LEDGERBAL  The account balance at the end date of transactions.
    .AVAILBAL   The available balance at the end date of transactions.
    .CURDEF     The currency code of the account.
-
-The following derived from .INTBID and a bank list in the script:
-
-   .BNS        Short-form name of Bank
-   .BNM        Short-form name of Bank
-   .BNL        Long-form name of Bank
 
 These are defived from the account number in .ACCTID
 
@@ -196,7 +213,7 @@ These are derived from the OFX's native DTPOSTED tag
 
 # format used for naming output files
 jq_filename_format='
-	.BNS + "-" + .ACCTSFX + " transactions from " + .DSTART + " to " + .DEND
+	.FIORG + "-" + .ACCTSFX + " transactions from " + .DSTART + " to " + .DEND
 '
 
 # format used for renaming ofx files, if blank will default to jq_filename_format
@@ -204,7 +221,7 @@ jq_rename_format=''
 
 # format of info string
 jq_info_format='
-	.BNL + ", account " + .ACCTID + ", from " +
+	.FIORG + ", account " + .ACCTID + ", from " +
 	.DSTART + " to " + .DEND + "."'
 
 # these three jq arrays should correspond to the same output columns
@@ -226,7 +243,7 @@ jq_hash_header='"HASH"'
 # columns values
 jq_txn_fields_array='
 	[
-		(.BNS + "-" + .ACCTSFX),
+		( (.FIORG | split(" ") | .[0]) + "-" + .ACCTSFX ),
 		.FITID,
 		.DPOSTED,
 		.DESC,
@@ -237,12 +254,17 @@ jq_txn_fields_array='
 
 # parsed by miller(mlr) to generate a hash value
 mlr_hash_definition='md5($1 . $2)'
+# currenly the hash is a function of values in other columns
+# and is added to the row as a new column
+# in the future, this may change to performing a hash
+# of a single column and replacing that field with the hash
+
 
 # column footer (used to indicate closing balance
 # a hash column will always be "" in the footer
 jq_balance_fields_array='
 	[
-		(.BNS + "-" + .ACCTSFX),
+		(.FIORG + "-" + .ACCTSFX),
 		"BALANCE",
 		.LEDGERD,
 		.LEDGERBAL,
@@ -283,14 +305,19 @@ define_error 65 BAD_PRESET  "'%s' is not a valid preset."
 define_error 66 BAD_JQ_FRAG "Can't parse jq fragment: %s"
 define_error 67 BAD_JQ_ARRY "Can't parse jq fragment: %s\n       Perhaps you forgot to enclose an array with []?"
 define_error 68 NO_FILE     "No file specified."
+define_error 69 NO_FIDIR    "Can't read list of financial institutions: '%s'."
 # PROBLEMS WITH FILE ACCESS
-define_error 71 BAD_FILE    "File '%s' not found."
+define_error 71 BAD_FILE    "File '%s' not found."\
 define_error 72 UNREADABLE  "File '%s' is unreadable."
 # PROGRAMMING ERROR
 define_error 99 INTERNAL    "Internal error on line %s. This is very bad."
-define_error 98 UNEXPECTED  "Unexpected error. This is very bad.\n  Command:     %s\n  Line Number: %s\n  Function:    %s\n  Exit Code:   %s"
+define_error 98 UNEXPECTED  "Unexpected error.\n  Exit Code:   %s\n  Line Number: %s\n  Function:    %s\n  Command:     %s"
 
-trap 'die UNEXPECTED "$BASH_COMMAND" "$LINENO" "${FUNCNAME[0]}" "$?"' ERR
+# this will catch unexpected errors
+trap 'die UNEXPECTED "$?" "$LINENO" "${FUNCNAME[0]}" "$('"
+	tr $'\n' '⮐' <<< "'"$BASH_COMMAND"'" |
+	sed -Ee 's/^(.{30}).*$/\1.../' -e 's/⮐$//'
+"')" ' ERR
 
 
 # global variable of filename of ofx file currently being processed
@@ -324,6 +351,7 @@ main(){
 		}
 		raw_json=$(xq -j <<<"$xml")
 		json=$(normalize_json <<<"$raw_json")
+		has_fiorg "$json" || json=$(set_fiorg "$json")
 
 		case "${SUBCOMMAND:-transactions}" in
 		xml) echo "$xml";;
@@ -343,22 +371,80 @@ main(){
 	then die BAD_XML "$failed of $# files"
 	fi
 }
+has_fiorg(){ local json_to_test="$1"
+	[[ -n "$(jq -r '.FIORG' <<<"$json_to_test")" ]]
+}
+set_fiorg(){ local json_to_fix="$1" fifid fiorg
 
+	fifid="$(jq -r '.FIFID' <<<"$json_to_fix")"
+
+	if [[ -n "${FIDIR_FILE:-}" ]]
+	then
+		if [[ -f "$FIDIR_FILE" ]]
+		then
+			fiorg="$( awk -F$'\t' \
+				-v id="$fifid" \
+				-v re="${FIORG_REGEX_DELETE:-}" '
+					$1==sprintf("%05d",id){
+						if (re!=""){ sub(re,"",$4) }
+						printf($4)
+					}
+				' "$FIDIR_FILE"
+			)"
+		else
+			warn "Can't read list of financial institutions: '$FIDIR_FILE'."
+		fi
+	fi
+
+	# add FIORG, to root and to TRANSACTIONS
+	jq --arg fiorg "${fiorg:-$fifid}" '
+		.FIORG=$fiorg
+		| .TRANSACTIONS=(
+			.TRANSACTIONS | map(. + { FIORG: $fiorg })
+		)' <<<"$json_to_fix"
+}
 parse_args(){
-	set -e
+	if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]
+	then
+		usage
+		exit 0
+	fi
+
+	OPTIND=0
+	while getopts ":hHD:" opt
+	do
+		case "$opt" in
+
+		h)
+			usage
+			exit 0
+			;;
+		H)
+			available_properties
+			exit 0
+			;;
+
+		D)
+			FIDIR_FILE="$OPTARG"
+			[[ -f "$FIDIR_FILE" && -r "$FIDIR_FILE" ]] ||
+				die NO_FIDIR
+			;;
+
+		:) die NO_OPTARG "$OPTARG";;
+		\?) die BAD_OPT "$OPTARG";;
+		*) die_hard
+
+		esac
+	done
+	to_shift=$(( OPTIND - 1 ))
+	shift $to_shift
+	OPTIND=0
+
 	TABLE_TYPE="csv"
 	case "${1:-}" in
 	'')
 		usage
 		exit 1
-		;;
-	-h|--help)
-		usage
-		exit 0
-		;;
-	-H)
-		available_properties
-		exit 0
 		;;
 	tsv)
 		TABLE_TYPE="tsv"
@@ -400,7 +486,6 @@ parse_args(){
 			esac
 		done
 		;;
-
 	info) shift
 		SUBCOMMAND=info
 		while getopts ":F:P:" opt
@@ -466,8 +551,8 @@ parse_args(){
 		else
 			die BAD_CMD "$1"
 		fi
-esac
-	return $OPTIND
+	esac
+	return $(( to_shift + OPTIND ))
 }
 
 print_info(){
@@ -611,11 +696,14 @@ normalize_json(){
 			"FILENAME": "'"$(basename "$ofx")"'",
 			"BASENAME": "'"$(basename "-s.ofx" "$ofx")"'"
 			}' \
-		--argjson fidir "$jq_fidir" \
+		--argjson fidir "$(fidir_json)" \
 		--arg desc_delim "$jq_description_delimiter" '
 
 def add_missing_cents:
 	gsub("^(?<a>-?\\d+)$";"\(.a).00") | gsub("^(?<a>-?\\d+\\.\\d)$";"\(.a)0")
+;
+def pad_left($pad_with;$pad_to):
+	$pad_with * ( $pad_to - length ) + .
 ;
 def to_date_time($digits):
 	($digits[0:4]+"-"+$digits[4:6]+"-"+digits[6:8]+"T"+digits[8:10]+":"+digits[10:12]+":"+digits[12:14])
@@ -626,11 +714,6 @@ def to_date($digits):
 def to_time_zone($digits):
 	$digits | gsub("^[0-9.]*\\[";"") | gsub(":[A-Z]*\\]";"")
 ;
-def add_derived_bank_names($s): $s | . + {
-	BNS: $fidir[$s.INTBID].short,
-	BNM: $fidir[$s.INTBID].medium,
-	BNL: $fidir[$s.INTBID].long
-};
 def file_info: {
 	BANKID: ((.BANKACCTFROM.BANKID // "")+(.CCACCTFROM.BANKID // "")),
 	ACCTID: ((.BANKACCTFROM.ACCTID // "")+(.CCACCTFROM.ACCTID // "")),
@@ -671,12 +754,19 @@ def derived_transaction_fields: {
 		.TRNAMT | add_missing_cents
 	)
 };
-def get_intbid: { INTBID: (.SIGNONMSGSRSV1.SONRS.FI.FID // "") };
+def bank_info: {
+	FIFID: (.SIGNONMSGSRSV1.SONRS.FI.FID // "" | pad_left("0";5) | sub("00000";"") ),
+	FIORG: (.SIGNONMSGSRSV1.SONRS.FI.ORG // "")
+};
+def add_missing_org:
+	if .FIORG//"" == "" then .FIORG = ($fidir[.FIFID//""] // "") end
+;
+
 def wrap: if type == "array" then . else [.] end;
 def first: if type == "array" then .[0] else . end;
 
 .OFX
-| $file + ( add_derived_bank_names(get_intbid) ) as $props
+| ( ($file + bank_info) | add_missing_org ) as $props
 |
 if has("BANKMSGSRSV1") then
 	( $props + { ACCTTYPE: "Bank" } ) as $props
